# Form implementation generated from reading ui file 'Main_win.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(506, 666)
        font = QtGui.QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(30, 40, 201, 31))
        self.comboBox.setObjectName("comboBox")
        self.widget_benefits = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_benefits.setGeometry(QtCore.QRect(20, 110, 241, 151))
        self.widget_benefits.setObjectName("widget_benefits")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.widget_benefits)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 191, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_benefits = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_benefits.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_benefits.setObjectName("verticalLayout_benefits")
        self.label_benefits = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_benefits.setGeometry(QtCore.QRect(30, 80, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_benefits.setFont(font)
        self.label_benefits.setObjectName("label_benefits")
        self.label_readings = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_readings.setGeometry(QtCore.QRect(30, 280, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_readings.setFont(font)
        self.label_readings.setObjectName("label_readings")
        self.label_device = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_device.setGeometry(QtCore.QRect(40, 20, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_device.setFont(font)
        self.label_device.setObjectName("label_device")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 400, 291, 81))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_readings = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_readings.setGeometry(QtCore.QRect(30, 320, 281, 21))
        self.lineEdit_readings.setObjectName("lineEdit_readings")
        self.label_type_device = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_type_device.setGeometry(QtCore.QRect(30, 370, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_type_device.setFont(font)
        self.label_type_device.setObjectName("label_type_device")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 540, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 540, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 506, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_benefits.setText(_translate("MainWindow", "Доступные льготы:"))
        self.label_readings.setText(_translate("MainWindow", "Введите показания:"))
        self.label_device.setText(_translate("MainWindow", "Счетчик:"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_type_device.setText(_translate("MainWindow", "Тип счетчика:"))
        self.pushButton.setText(_translate("MainWindow", "Рассчитать"))
        self.pushButton_2.setText(_translate("MainWindow", "Записать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
